# To update:
# Copy README and replace `^- \[(.*)\].*` with `plugins.'$1'.github = "$1"`

plugins.'zsh-users/zsh-autosuggestions'.github = "zsh-users/zsh-autosuggestions"
plugins.'wting/autojump'.github = "wting/autojump"
plugins.'zsh-users/zsh-syntax-highlighting'.github = "zsh-users/zsh-syntax-highlighting"
plugins.'StackExchange/blackbox'.github = "StackExchange/blackbox"
plugins.'sobolevn/git-secret'.github = "sobolevn/git-secret"
plugins.'b4b4r07/enhancd'.github = "b4b4r07/enhancd"
plugins.'fcambus/ansiweather'.github = "fcambus/ansiweather"
plugins.'chriskempson/base16-shell'.github = "chriskempson/base16-shell"
plugins.'supercrabtree/k'.github = "supercrabtree/k"
plugins.'zsh-users/zsh-history-substring-search'.github = "zsh-users/zsh-history-substring-search"
plugins.'wfxr/forgit'.github = "wfxr/forgit"
plugins.'zdharma/fast-syntax-highlighting'.github = "zdharma/fast-syntax-highlighting"
plugins.'iam4x/zsh-iterm-touchbar'.github = "iam4x/zsh-iterm-touchbar"
plugins.'unixorn/git-extra-commands'.github = "unixorn/git-extra-commands"
plugins.'MichaelAquilina/zsh-you-should-use'.github = "MichaelAquilina/zsh-you-should-use"
plugins.'mfaerevaag/wd'.github = "mfaerevaag/wd"
plugins.'zsh-users/zaw'.github = "zsh-users/zaw"
plugins.'Tarrasch/zsh-autoenv'.github = "Tarrasch/zsh-autoenv"
plugins.'mafredri/zsh-async'.github = "mafredri/zsh-async"
plugins.'djui/alias-tips'.github = "djui/alias-tips"
plugins.'agkozak/zsh-z'.github = "agkozak/zsh-z"
plugins.'changyuheng/fz'.github = "changyuheng/fz"
plugins.'b4b4r07/emoji-cli'.github = "b4b4r07/emoji-cli"
plugins.'Tarrasch/zsh-bd'.github = "Tarrasch/zsh-bd"
plugins.'Vifon/deer'.github = "Vifon/deer"
plugins.'zdharma/history-search-multi-word'.github = "zdharma/history-search-multi-word"
